itech/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from noobnews import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^noobnews/', include('noobnews.urls')),
    # above maps any URLs starting
    # with noobnews/ to be handled by
    # the noobnews application
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

noobnews/urls.py
from django.conf.urls import url
from django.conf.urls import include
from noobnews import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^cart/$', views.video_game_list_add, name='cart'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^videogamesuggest/(?P<videogame_name_slug>[\w\-]+)/$',
        views.suggestChanges, name='suggestChanges'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^videogame/(?P<videogame_name_slug>[\w\-]+)/$',
        views.show_videogame, name='show_videogame'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^reset_password/$', views.reset_password, name="reset_password"),
    url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.reset_password_confirm,name='reset_password_confirm'),
    url(r'^register/$', views.register, name='register'),
    url(r'^contact_us/$', views.contact_us, name='contact_us'),
    url('', include('social_django.urls', namespace='social')),
    url(r'^top40/$', views.top40, name='top40'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

noobnews/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.template.defaultfilters import slugify
from django.conf import settings
from django.db.models.signals import pre_save, post_save, m2m_changed


# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Default images
    user_profile_image = models.ImageField(
        default='NoProfile.jpg', upload_to='static/profile_images')
    game_library_image = models.ImageField(
        default='default_videogame.jpg', upload_to='static/video_game_default')
    player_tag = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return f'{self.user.username}'


class Genre(models.Model):
    genre_id = models.IntegerField(unique=True, primary_key=True)
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class VideoGame(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    genre = models.ForeignKey(Genre)
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(blank=True)
    description = models.CharField(max_length=1000)
    rating = models.IntegerField(default=0)
    release = models.DateField(("Date"), default=date.today)
    developer = models.CharField(max_length=128)
    publisher = models.CharField(max_length=128)
    image = models.ImageField(default="")
    youtubeurl = models.CharField(max_length=300)
    speedRun = models.CharField(max_length=300)
    trivia = models.CharField(
        max_length=300, default="There are no Trivia available for this game at the moment")
    cheats = models.CharField(
        max_length=300, default="There are no Cheats available for this game at the moment")
    easter_eggs = models.CharField(
        max_length=300, default="There are no Easter Eggs available for this game at the moment")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(VideoGame, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'videogames'

    def __str__(self):
        return self.name


class Review(models.Model):
    reviews_id = models.IntegerField(unique=True, primary_key=True)
    videogame = models.ForeignKey(VideoGame)
    user_id = models.ForeignKey(UserProfile)
    comments = models.CharField(max_length=300)
    publish_date = models.DateField(("Date"), default=date.today)
    comment_rating = models.IntegerField(default=0)

    def __str__(self):
        return self.videogame.name


# Manage library
class VideoGameListManager(models.Manager):

    def new_or_get(self, request):
        library_id = request.session.get("library_id", None)
        qs = self.get_queryset().filter(list_id=library_id)

        if qs.count() == 1:
            new_obj = False
            library_obj = qs.first()
            if request.user.is_authenticated() and library_obj.user is None:
                library_obj.user = request.user
                library_obj.save()
        else:
            user = request.user.userprofile
            library_obj = VideoGameList.objects.new(
                user=request.user.userprofile)
            new_obj = True
            request.session['library_id'] = library_obj.list_id
        return library_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            user_obj = user
        return self.model.objects.create(user=user_obj)

# Make a library for favorite games


class VideoGameList(models.Model):
    list_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(UserProfile, null=True)
    userLibrary = models.ManyToManyField(VideoGame, blank=True)
    game_library_image = models.ImageField(
        default='default_videogame.jpg', upload_to='static/video_game_default')

    objects = VideoGameListManager()

    def __str__(self):
        return str(self.list_id)


def m2m_changed_video_game_list(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        userLibrary = instance.userLibrary.all()
        instance.save()


m2m_changed.connect(m2m_changed_video_game_list,
                    sender=VideoGameList.userLibrary.through)


# class VideoExtraInfo(models.Model):
#     videogame_id = models.ForeignKey(VideoGame)
#     trivia = models.CharField(max_length=300, default="There is no Trivia available for this game at the moment")
#     cheats = models.CharField(max_length=300, default="There is no Cheats available for this game at the moment")
#     credits = models.CharField(max_length=300, default="There is no Credits available for this game at the moment")
#     triviaPicture = models.CharField(max_length=300, default="There is no Trivia available for this game at the moment")
#     cheatPicture = models.CharField(max_length=300, default="There is no Cheats available for this game at the moment")
#     creditPicture = models.CharField(max_length=300, default="There is no Credits available for this game at the moment")
#
#     def __str__(self):
#         return self.trivia

class ratingValue(models.Model):
    number = models.IntegerField(default=0)
    value = models.FloatField(default=0)

    def __str__(self):
        return self.number


class score(models.Model):
    videogame = models.ForeignKey(VideoGame)
    score = models.FloatField(default=0)

    def __str__(self):
        return self.videogame

noobnews/forms.py
from django import forms

from string import Template
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from crispy_forms.bootstrap import PrependedText
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from noobnews.models import UserProfile, Review, VideoGame, VideoGameList


class UserForm(forms.ModelForm):
    first_name = forms.CharField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Full name'}))
    # name_icon = forms.CharField()
    email = forms.CharField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Email'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={'placeholder': 'Create password'}))

    repeat_password = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={'placeholder': 'Repeat password'}))

    class Meta:
        model = User
        fields = ('first_name', 'email', 'password')

    helper = FormHelper()
    helper.layout = Layout(
        # first_name,
        PrependedText(
            'first_name', '<i class="fa fa-user"></i>'),
        # email,
        PrependedText(
            'email', '<i class="fa fa-envelope"></i>'),
        # password,
        PrependedText(
            'password', '<i class="fa fa-lock"></i>'),
        # repeat_password,
        PrependedText(
            'repeat_password', '<i class="fa fa-lock"></i>'),
    )


class UserProfileForm(forms.ModelForm):
    player_tag = forms.CharField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Player tag'}))

    user_profile_image = forms.FileField(label='', required=False)

    class Meta:
        model = UserProfile
        fields = ('player_tag', 'user_profile_image',)

    helper = FormHelper()
    helper.layout = Layout(
        # player_tag,
        PrependedText(
            'player_tag', '<i class="fa fa-gamepad"></i>'),
        # 'user_profile_image',
        PrependedText(
            'user_profile_image', '<i class="fa fa-image"></i>'),



    )

    helper.form_tag = False

# update my name in user profile page


class UserUpdateForm(forms.ModelForm):

    player_tag = forms.CharField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Change my user name'}))

    class Meta:
        model = UserProfile
        fields = ('player_tag',)

# update my picture in user profile page


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('user_profile_image',)


class VideoImageUpdateForm(forms.ModelForm):
    class Meta:
        model = VideoGameList
        fields = ('game_library_image',)


class PasswordResetRequestForm(forms.Form):
    email_or_playertag = forms.CharField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Email or player tag'}))


class SetPasswordForm(forms.Form):
    error_messages = {
        'password_mismatch': ("The two password fields didn't match."),
    }
    new_password1 = forms.CharField(label='',
                                    widget=forms.PasswordInput(attrs={'placeholder': 'New password'}))
    new_password2 = forms.CharField(label='',
                                    widget=forms.PasswordInput(attrs={'placeholder': 'Confirm new  password'}))

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2


class ContactForm(forms.Form):
    full_name = forms.CharField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Full name'}))
    email = forms.CharField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Email'}))
    type_suggestion = forms.ChoiceField(label='',
                                        choices=[(0, '--Select the suggestion type--'),
                                                 (1, 'Suggest games to add'), (2, 'Suggest changes to a game')])
    video_games_list = forms.ModelChoiceField(label='', queryset=VideoGame.objects.all().order_by('name'),
                                              empty_label="--Select a game--",
                                              to_field_name="id",
                                              required=False)
    contact_message = forms.CharField(label='', widget=forms.Textarea(
        attrs={'placeholder': 'Message'}))

    helper = FormHelper()
    helper.layout = Layout(
        PrependedText(
            'full_name', '<i class="fa fa-user"></i>'),
        PrependedText(
            'email', '<i class="fa fa-envelope"></i>'),
        PrependedText(
            'contact_message', '<i class="fas fa-comments"></i>'),
    )


class SuggestForm(forms.ModelForm):

    class Meta:
        model = VideoGame
        fields = ('name', 'description', 'publisher',)


class ReviewForm(forms.ModelForm):
    comment_rating = forms.ChoiceField(choices=[(x, x) for x in range(1, 6)])
    comments = forms.CharField(label='', widget=forms.Textarea(
        attrs={'placeholder': 'Please write your comment in here '}))
    #user_id= forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'User_id'}))

    class Meta:
        model = Review
        fields = ('comment_rating', 'comments',)

templates/noobnews/backup.html
<div class="homecontent">
  <div class="block x1"><img style="height: inherit; width:inherit;" src="/static/videogameImages/breathOfTheWild.jpg"></div>
  <div class="block x2">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="width:100%; height:100%;" >
      <!-- Wrapper for slides -->
      <div class="carousel-inner" style="width:100%; height:100%;">
        <div class="item active" style="width:100%; height:100%;">
          <img style="height: inherit; width:inherit;" src="/static/videogameImages/breathOfTheWild.jpg" alt=""">
        </div>
        {% for v in top40List %}
        <div class="item" style="width:100%; height:100%;">
          <img style="height: inherit; width:inherit;" src="{{ v.image }}" alt="{{ v.name }}" >
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="block x3">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="width:100%; height:100%;" >
      <!-- Wrapper for slides -->
      <div class="carousel-inner" style="width:100%; height:100%;">
        <div class="item active" style="width:100%; height:100%;">
          <img style="height: inherit; width:inherit;" src="/static/videogameImages/breathOfTheWild.jpg" alt=""">
        </div>
        {% for n in newList %}
        <div class="item" style="width:100%; height:100%;">
          <img style="height: inherit; width:inherit;" src="{{ n.image }}" alt="{{ n.name }}" >
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="block x4">4</div>
  <div class="block x5">5</div>
</div>

templates/noobnews/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!-- sources for Video game images are in populate_noobnews.py script-->
<html lang="en">
  <head>
    <link rel="stylesheet" href="/static/css/login.css" />
    <link rel="stylesheet" href="/static/css/noobnews.css" />
    <link rel="stylesheet" href="/static/css/top40.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
      function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
      }
      function searchBar() {
        document.getElementById("search").style.visibility="visible";
      }

      function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
      }
   </script>
    <title>
      {% block title_block %}Noob News{% endblock %}</title>
  </head>
  <body background="/static/images/Background.png" style="background-attachment: fixed; background-size: cover;   background-repeat: no-repeat;">
    <!-- https://www.etq-amsterdam.com/ -->
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      {% if user.is_authenticated %}
        <div class="w3-container">
          <center>
            <div class="profile-pic">
                <img src="{{ user.userprofile.user_profile_image.url }}" ; style="width:150px;  height: 150px;" />
            </div>
          </center>
          <br><br>
        </div>
      {% endif %}
      <div class="w3-bar-block">
        <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-padding "><i class="fas fa-file-upload fa-fw w3-margin-right"></i>Home</a>
        <a href="{% url 'top40' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-padding" id="ViewWork"><i class="fas fa-history fa-fw w3-margin-right"></i>Top 40</a>
        <a  href="{% url 'profile' %}" class="w3-bar-item w3-button w3-padding "><i class="fas fa-mail-bulk fa-fw w3-margin-right"></i>Profile</a>
         {% if user.is_authenticated %}
              <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-padding"><i class="fas fa-sign-out-alt fa-fw w3-margin-right"></i>Logout</a>
            {% else %}
              <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-padding"><i class="fas fa-sign-in-alt fa-fw w3-margin-right"></i>Login</a>
          {% endif %}
        <a href="{% url 'contact_us' %}" class="w3-bar-item w3-button w3-padding"><i class="fas fa-envelope fa-fw w3-margin-right"></i>Contact us</a>
      </div>

    </div>
    <br />
    <span
      style="font-size:30px;cursor:pointer; font-size: 90%; font-family:'Batang'; padding-left:40px; color:black" onclick="openNav()">&#9776;</span>
    <div id="noob-navigator">
      <div class="row">
        <!-- https://codepen.io/CBeghin/pen/HeuiF-->
        <!--Search Feacture: results are shown in the cats div! -->
        <form class="search" id="search">
          <input class="suggestion" type="text" name="suggestion" value="" id="suggestion" placeholder="Find a Game"/>
          <div class="results" id="cats">
          </div>
        </form>
        <a href="{% url 'profile' %}" class="user"> <i class="fas fa-user"></i></a>
        <a onclick='searchBar()' class="searchicon"> <i class="fas fa-search"></i></a>
      </div>
    </div>

   <div class="container">
      {% include 'noobnews/messages.html' %}
      {% block body_block %}
      {% endblock %}
    </div>
  </body>

  <!-- Bootstrap core JavaScript ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "js/noobnews-jquery.js" %}"></script>
<script src="{% static "js/noobnews-ajax.js" %}"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'>

{% block video %}
<script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
<script src="{% static "js/top40.js" %}"></script>
<script src="https://npmcdn.com/bootstrap@4.0.0-alpha.5/dist/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"> </script>
<script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"> </script>
<script src= "http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"> </script>
{% endblock %}
{% block videoG %}
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"/>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"crossorigin="anonymous"></script>
  <script src="{% static "js/top40.js" %}"></script>
{% endblock %}
</html>

templates/noobnews/cart.html
{% extends 'noobnews/base.html' %} {% load staticfiles %} {% block body_block %}

<h3>test</h3>

{% if user.is_authenticated %}

<h3>test</h3>
{% for s in game %}

{{ s.name }}

{% endfor %} {% endif %} {% endblock %}
<!------ Test library funtionality ---------->

templates/noobnews/cats.html
<ul>
  {% if cats %}
  {% for c in cats %}
  {% if c == act_cat %}


  <a href="{% url 'show_videogame' c.slug %}">{{ c.name }}</a></div>

  {% else %}
  <li><a href="{% url 'show_videogame' c.slug %}">{{ c.name }}<br /><span></span></a></li>

  {% endif %}
  {% endfor %}
  {% else %}
  <li><a href=""> There are no games that match your search term</a><li>
  {% endif %}
</ul>

templates/noobnews/contact_form.html
{% extends 'noobnews/base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block title_block%} Contact form {% endblock %}
{% block body_block %}
<script src="../../static/js/login.js"></script>
<script>
    $(document).ready(function () {
        var video_game_dropdown = $("#id_video_games_list");
        var suggestion_type = $("#id_type_suggestion");

        video_game_dropdown.addClass("d-none");
        suggestion_type.change(function () {
            if (suggestion_type.val() != 2) {
                video_game_dropdown.addClass("d-none");
            } else {
                video_game_dropdown.removeClass("d-none");
            }
        });
    });
</script>
<div class="row justify-content-center">
  <div class="card-login w-25">
    <article class="card-body">
      <h4 class="card-title mb-4 mt-1">Contact Form</h4>
      <form id="contact_form" method="post" action="{% url 'contact_us' %}">
        {% csrf_token %}
        {{ contact_form | crispy }}
        <!-- form-group// -->
        <div class="row align-items-center">
          <div class="col-md-6">
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">
                Send message
              </button>
            </div>
            <!-- form-group// -->
          </div>
          <div class="col-md-6 text-right">
            <a class="small" href="/">Return to the Home page</a>
          </div>
        </div>
        <!-- .row// -->
      </form>
    </article>
  </div>
  <!-- card.// -->
</div>
{% endblock %}

templates/noobnews/login.html
{% extends 'noobnews/base.html' %}
{% load staticfiles %} 
{% block title_block%}
Login 
{% endblock %} 
{% block body_block %}
<script src="../../static/js/login.js"></script>
<div class="row justify-content-center">
  <div class="card-login w-25">
    <article class="card-body">
      <a href="{% url 'register' %}" class="float-right btn btn-outline-primary"
        >Sign up</a
      >
      <h4 class="card-title mb-4 mt-1">Sign in</h4>
      <p>
        <a
          href="{% url 'social:begin' 'twitter' %}"
          class="btn btn-block btn-outline-info"
        >
          <i class="fab-login fa-twitter"></i>
          Login via Twitter
        </a>
      </p>
      <hr />
      <form id="login_form" method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="form-group">
          <input
            name="mail"
            class="form-control"
            required
            placeholder="Email"
            type="email"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group">
          <input
            name="password"
            class="form-control"
            required
            placeholder="Password"
            type="password"
          />
        </div>
        <!-- form-group// -->
        <div class="row align-items-center">
          <div class="col-md-6">
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">
                Login
              </button>
            </div>
            <!-- form-group// -->
          </div>
          <div class="col-md-6 text-right">
            <a class="small" href="/">Return to the Home page</a>
            <a class="small" href="{% url 'reset_password' %}">Forgot password?</a>
          </div>
        </div>
        <!-- .row// -->
      </form>
    </article>
  </div>
  <!-- card.// -->
</div>
{% endblock %}

templates/noobnews/videogameSuggestChanges.html
<!DOCTYPE html>
{% extends 'noobnews/base.html' %}
{% load staticfiles %}
<html lang="en">

<!--This page is the edit video game screen, this will allow the games to be edited  -->
<head>
  <meta charset="UTF-8">
  {% block title_block %}{{ videoGame.name }}{% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">


  {% block videoG %} {% endblock %}
  <link rel="stylesheet" href="/static/css/videoGameBootstrap.css">
  <link rel="stylesheet" href="/static/css/noobnews.css">



</head>


{% block body_block %}


</div>
<!-- Will post the game to the following URL   -->
<form method="POST" action="/noobnews/videogamesuggest/{{ videoGame.slug }}/">{% csrf_token %}

<div class="fond"><span class="s2"></span></div>
<div class="contact">
  <main>
    <div class="card">
      <div class="thumbnail"><img style="height: inherit; width:inherit;" class="left" src="{{ videoGame.image }}" /></div>
      <div class="right">
<h1></h1>
        <!--The form is identical to the video game page but the fields are input values meaning that they can be changed  -->
        <input type="text" size=20 name= "name" id="id_name" value="{{ videoGame.name }}">
        <div>
            <input type="text" name= "publisher" id="id_publisher" class="input4" value="{{ videoGame.publisher }}">

          <br>
        </div>
        <br>
        <div class="separator"></div>
        <br>
          <textarea class='textarea2' name="description" id="id_description">{{ videoGame.description }}</textarea>

      </div>
      <!-- We dont want the user to change the rating- this is generated by the system -->
      <h5>{{ videoGame.rating }}/5</h5>

      <button type="Save">
        <span>Confirm Changes</span>
        <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
          <g class="nc-icon-wrapper" fill="#444444">
            <path d="M14.83 30.83L24 21.66l9.17 9.17L36 28 24 16 12 28z"></path>
          </g>
        </svg>


      </button>

    </div>


  </main>

</form>


    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.min.js'></script>

  </nav>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto+Condensed'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css'>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
  <script src="/static/js/index.js"></script>

  {% endblock %}